apiVersion: v1
kind: Service
metadata:
  name: chat-ollm
  namespace: ollm
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30100
  selector:
    app: chat-ollm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-ollm
  namespace: ollm
spec:
  selector:
    matchLabels:
      app: chat-ollm
  replicas: 1
  template:
    metadata:
      labels:
        app: chat-ollm
    spec:
      containers:
        - name: chat-ollm
          image: 192.168.2.101:5000/chat-ollm:1.0.0
          ports:
            - containerPort: 80
